# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib MatrixProd, .registration = TRUE
#' @importFrom Rcpp evalCpp
NULL

# Экспорт нативных функций для внутреннего использования
`_get_performance_info` <- function() {
    .Call("get_performance_info")
}

`_rust_mmTiny_cpp` <- function(A, B) {
    .Call("rust_mmTiny_cpp", A, B)
}

`_cpp_mmAccelerate` <- function(A, B) {
    .Call("cpp_mmAccelerate", A, B)
}
