# Generated by using Rcpp::compileAttributes() -> do not edit by hand

#' @useDynLib MatrixProd, .registration = TRUE
#' @importFrom Rcpp evalCpp
NULL

# Внутренняя функция для получения информации о производительности
`_get_performance_info` <- function() {
    .Call("get_performance_info")
}

# Внутренние функции для умножения матриц с использованием Rust
`_rust_mmTiny_cpp` <- function(A, B) {
    .Call("rust_mmTiny_cpp", A, B)
}

`_rust_mmBlocked_cpp` <- function(A, B) {
    .Call("rust_mmBlocked_cpp", A, B)
}

`_rust_mmAuto_cpp` <- function(A, B) {
    .Call("rust_mmAuto_cpp", A, B)
}

# Внутренняя функция для умножения матриц с использованием C++ и Accelerate
`_cpp_mmAccelerate` <- function(A, B) {
    .Call("cpp_mmAccelerate", A, B)
}

# Внутренние функции для умножения матриц с использованием GPU
`_gpu_mmMetal` <- function(A, B) {
    .Call("gpu_mmMetal", A, B)
}

`_is_metal_available` <- function() {
    .Call("is_metal_available")
}
